services:
  - type: web
    name: adu-travel-api
    env: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: python3 server.py
    plan: free
    envVars:
      - key: PORT
        value: "8766"
